### ISSUE TITLE
Configuring an invalid transport on an iFC causes dial-a-boot

### ISSUE THREAD

**Issue by mirw** [Metaswitch/sprout#105]
In a moment of madness, I configured my iFC's ServerName element to be ...;transport=sip.  "sip" is obviously not a valid transport.  Unfortunately, sprout then crashed as follows whenever I tried to invoke this AS.

```
Thread 19 (Thread 0x7f9cf57e2700 (LWP 12653)):
#0  0x00007f9d1cd0348d in waitpid () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f9d1cc8929e in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f9d1cc896b0 in system () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x000000000041e1d3 in Logger::backtrace (this=0x1f5a680, data=<optimized out>) at logger.cpp:190
#4  0x000000000048210f in Log::backtrace (fmt=<optimized out>) at log.cpp:135
#5  0x0000000000490ff9 in exception_handler (sig=6) at main.cpp:424
#6  <signal handler called>
#7  0x00007f9d1cc7a425 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#8  0x00007f9d1cc7db8b in abort () from /lib/x86_64-linux-gnu/libc.so.6
#9  0x00007f9d1cc730ee in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#10 0x00007f9d1cc73192 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#11 0x00000000004b241a in pjsip_transport_get_type_from_name (name=0x7f9cd80b0ef8) at ../src/pjsip/sip_transport.c:283
#12 0x00000000004ae603 in get_dest_info (target_uri=0x7f9cd80b0e48, pool=0x7f9cd80ae500, dest_info=0x7f9cf57e1470) at ../src/pjsip/sip_util.c:848
#13 0x00000000004ae9d5 in pjsip_process_route_set (tdata=0x7f9cd80ae5a8, dest_info=0x7f9cf57e1470) at ../src/pjsip/sip_util.c:1001
#14 0x00000000004af441 in pjsip_endpt_send_request_stateless (endpt=0x7f9d164cf0b8, tdata=0x7f9cd80ae5a8, token=0x7f9cd80b0568, cb=0x4bffb2 <send_msg_callback>) at ../src/pjsip/sip_util.c:1353
#15 0x00000000004c0cb5 in tsx_send_msg (tsx=0x7f9cd80b0568, tdata=0x7f9cd80ae5a8) at ../src/pjsip/sip_transaction.c:2104
#16 0x00000000004c1439 in tsx_on_state_null (tsx=0x7f9cd80b0568, event=0x7f9cf57e15a0) at ../src/pjsip/sip_transaction.c:2343
#17 0x00000000004bfeaf in pjsip_tsx_send_msg (tsx=0x7f9cd80b0568, tdata=0x7f9cd80ae5a8) at ../src/pjsip/sip_transaction.c:1716
#18 0x000000000042463c in UACTransaction::send_request (this=0x7f9cd808a140) at stateful_proxy.cpp:2902
#19 0x0000000000424e41 in UASTransaction::init_uac_transactions (this=0x7f9cd8004480, targets=...) at stateful_proxy.cpp:2549
#20 0x0000000000427235 in UASTransaction::handle_outgoing_non_cancel (this=0x7f9cd8004480, target=0x7f9cd808a480) at stateful_proxy.cpp:1964
#21 0x00000000004276dd in UASTransaction::handle_non_cancel (this=0x7f9cd8004480, serving_state=...) at stateful_proxy.cpp:1769
#22 0x0000000000428c32 in process_tsx_request (rdata=0x7f9ce00e6d08) at stateful_proxy.cpp:532
#23 0x0000000000429b1b in proxy_on_rx_request (rdata=0x7f9ce00e6d08) at stateful_proxy.cpp:234
#24 0x00000000004abcb5 in pjsip_endpt_process_rx_data (endpt=0x7f9d164cf0b8, rdata=0x7f9ce00e6d08, p=0x7f9cf57e1e40, p_handled=0x0) at ../src/pjsip/sip_endpoint.c:885
#25 0x000000000041f632 in worker_thread (p=<optimized out>) at stack.cpp:363
#26 0x00000000004d8198 in thread_main (param=0x1f5db08) at ../src/pj/os_core_unix.c:523
#27 0x00007f9d1dcbfe9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#28 0x00007f9d1cd37ccd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#29 0x0000000000000000 in ?? ()
```

Sprout shouldn't handle this better.

**Comment by eleanor-merry** [comment]
Fixed by https://github.com/Metaswitch/pjsip-upstream/commit/86f50b49a09f5a1b562e5440140f0a68efeb7bee
