### ISSUE TITLE
Sprout crashing at low call rate with VoLTE TAS

### ISSUE THREAD

**Issue by plfrancis** [Metaswitch/sprout#1095]
Running 10 - 15 CPS traffic with 15,000 subscribers doing 5 minute registration causes Sprout to crash. The back-trace is shown below. A diagnostics bundle was collected.

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f08871ce688 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
(gdb) bt
#0  0x00007f08871ce688 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#1  0x00007f08871cf6f8 in _Unwind_Backtrace () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#2  0x00007f0886f04e26 in __GI___backtrace (array=<optimized out>, size=32) at ../sysdeps/x86_64/backtrace.c:109
#3  0x00000000004bbc7d in Logger::backtrace (this=0x270a010, data=<optimized out>) at /var/build/CC_7.0.0-WIP/cc/sprout/modules/cpp-common/src/logger.cpp:277
#4  0x0000000000571a4d in Log::backtrace (fmt=fmt@entry=0x6f28e0 "Signal %d caught") at /var/build/CC_7.0.0-WIP/cc/sprout/modules/cpp-common/src/log.cpp:185
#5  0x00000000005bda3c in signal_handler (sig=11) at main.cpp:1008
#6  <signal handler called>
#7  0x0000000000000038 in ?? ()
#8  0x00007f087c15552d in SCSCFSproutletTsx::on_rx_response (this=0x7f0824747170, rsp=0x7f085c71c680, fork_id=0) at scscfsproutlet.cpp:532
#9  0x00000000005b3825 in SproutletWrapper::rx_response (this=0x7f082459be50, rsp=0x7f085c71c118, fork_id=0) at sproutletproxy.cpp:1438
#10 0x00000000005b39e0 in SproutletProxy::UASTsx::tx_response (this=0x7f0824298220, downstream=downstream@entry=0x7f082499d0d0, rsp=0x7f085c71c118)
    at sproutletproxy.cpp:893
#11 0x00000000005b3c3f in SproutletWrapper::tx_response (this=this@entry=0x7f082499d0d0, rsp=<optimized out>) at sproutletproxy.cpp:1734
#12 0x00000000005b4078 in SproutletWrapper::process_actions (this=0x7f082499d0d0, complete_after_actions=<optimized out>) at sproutletproxy.cpp:1559
#13 0x00000000005b3839 in SproutletWrapper::rx_response (this=<optimized out>, rsp=<optimized out>, fork_id=<optimized out>) at sproutletproxy.cpp:1439
#14 0x00000000005b5abc in SproutletProxy::UASTsx::on_new_client_response (this=0x7f0824298220, uac_tsx=<optimized out>, rsp=0x7f085c71c118)
    at sproutletproxy.cpp:592
#15 0x000000000058cda6 in BasicProxy::UACTsx::on_tsx_state (this=0x7f08245a8370, event=0x7f0839fbab00) at basicproxy.cpp:1901
#16 0x000000000063f309 in tsx_set_state (tsx=0x7f08249b1d78, state=PJSIP_TSX_STATE_COMPLETED, event_src_type=PJSIP_EVENT_RX_MSG, event_src=0x7f0824a139c8)
    at ../src/pjsip/sip_transaction.c:1199
#17 0x0000000000642c96 in tsx_on_state_proceeding_uac (tsx=0x7f08249b1d78, event=0x7f0839fbabb0) at ../src/pjsip/sip_transaction.c:3007
#18 0x000000000064051b in pjsip_tsx_recv_msg (tsx=0x7f08249b1d78, rdata=0x7f0824a139c8) at ../src/pjsip/sip_transaction.c:1754
#19 0x000000000063e835 in mod_tsx_layer_on_rx_response (rdata=0x7f0824a139c8) at ../src/pjsip/sip_transaction.c:863
#20 0x00000000006280af in pjsip_endpt_process_rx_data (endpt=0x7f087da960b8, rdata=0x7f0824a139c8, p=0x7f0839fbad20, p_handled=0x0)
    at ../src/pjsip/sip_endpoint.c:893
#21 0x00000000005bacdd in worker_thread (p=<optimized out>) at thread_dispatcher.cpp:153
#22 0x00000000006a4e2e in thread_main (param=0x2e427f8) at ../src/pj/os_core_unix.c:523
#23 0x00007f08879e7182 in start_thread (arg=0x7f0839fbb700) at pthread_create.c:312
#24 0x00007f0886ef447d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by mirw** [comment]
The scenario is as follows.

*   A calls B
*   We invoke A's originating TAS.  It doesn't respond (it looks like it's completely dropped off the network).
*   Since the IFCs are configured to bypass the originating TAS, we move on and invoke B's terminating TAS.  It responds and the call goes through.
*   32s after we invoked A's originating TAS, we time out the attempt and retry it, this time to a different host.
*   We immediately chase this with a CANCEL to abandon it.  However, when the transactions unwind, we end up trying to resend an ACR that we've already sent, and this causes the crash.

There is a question here as to why the TAS isn't responding at all, but we should cope with that.

So, the issues here are.

*   We shouldn't retry 32s after we've abandoned an AS.  This is covered by #1080.
*   We shouldn't recover from this condition, and not try to update the ACR after it's already sent.  This is covered by this issue.

**Comment by mirw** [comment]
I think there's a simple and safe partial fix just never to retry a request on SIP timeout (i.e. after 32s).  After 32s without even ringing, it's pretty safe to assume that the call has failed and that there's no point in retrying.

This will eliminate the main path in which we send an INVITE chased by a CANCEL.  (It would still be possible to hit in some race conditions, but these should be very rare.)

We should still fix #1080 properly, and should also not try to update the ACR after it is sent.

**Comment by mirw** [comment]
I've coded the partial fix described above and it's with @bossmc for review.

**Comment by mirw** [comment]
@plfrancis, please can you test with the referenced fix?

**Comment by plfrancis** [comment]
This issue has not been observed in recent traffic runs/soaks. Closing.
