### ISSUE TITLE
Sprout crashes with segment trap on any ipsec registration

### ISSUE THREAD

**Issue by dcollins991** [Metaswitch/sprout#1176]
On the K load sprout will crash for any ipsec registration attempt.  I have the gather_diags output on both sprouts along with the SAS traces.

**Comment by mirw** [comment]
@dcollins991, thanks for raising.  Please can you elaborate on what your mean by an IPsec registration - is this using AKA authentication?

**Comment by dcollins991** [comment]
I meant to say AKA.  Earlier I had assumed I had a firewall issue for the ESP packets.  But everything is getting through for the registration.  Sprout crashes on the Register to be authenticated for AKA.  .

**Comment by dcollins991** [comment]
The diags and SAS traces are now out there.

**Comment by mirw** [comment]
The crash is at

```
Thread 147 (Thread 0x7fe6f9fcb700 (LWP 16345)):
#0  0x00007fe73c69db99 in __libc_waitpid (pid=31346, stat_loc=stat_loc@entry=0x7fe6f9fc7ee0, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40
#1  0x00007fe73c6232e2 in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:148
#2  0x00000000004cfe13 in Logger::backtrace (this=0xefcfb0, data=<optimized out>) at /var/build/CC_8.0.0-WIP/cc/sprout/modules/cpp-common/src/logger.cpp:292
#3  0x0000000000583d1d in Log::backtrace (fmt=fmt@entry=0x71868d "Signal %d caught") at /var/build/CC_8.0.0-WIP/cc/sprout/modules/cpp-common/src/log.cpp:185
#4  0x00000000005e0e2c in signal_handler (sig=11) at main.cpp:1076
#5  <signal handler called>
#6  0x000000000050d9a0 in authenticate_rx_request (rdata=0x7fe71401c258) at authentication.cpp:709
#7  0x000000000064b4cd in pjsip_endpt_process_rx_data (endpt=0x7fe72cce90b8, rdata=0x7fe71401c258, p=0x7fe6f9fcad10, p_handled=0x0) at ../src/pjsip/sip_endpoint.c:885
#8  0x00000000005cdced in worker_thread (p=<optimized out>) at thread_dispatcher.cpp:153
#9  0x00000000006c8154 in thread_main (param=0x177ade8) at ../src/pj/os_core_unix.c:523
#10 0x00007fe73d1ca182 in start_thread (arg=0x7fe6f9fcb700) at pthread_create.c:312
#11 0x00007fe73c6d747d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

authentication.cpp:709 is the last line of the following:

```
    if (!is_register)
    {
      // Challenged non-register requests must be SIP digest, so only one table
      // needed for this case.
      auth_stats_table = auth_stats_tables->non_register_auth_tbl;
    }
    else
    {
      if (!pj_strcmp2(&credentials->algorithm, "MD5"))
      {
        auth_stats_table = auth_stats_tables->sip_digest_auth_tbl;
      }
      else if (!pj_strcmp2(&credentials->algorithm, "AKAv1-MD5"))
      {
        auth_stats_table = auth_stats_tables->ims_aka_auth_tbl;
      }
    }
    auth_stats_table->increment_attempts();
```

It looks like we initialize auth_stats_table to NULL and then don't check for NULL here.

@alango, are you OK to take a look at this?

Also, it's worth considering whether it's right to initialize this to NULL.  If you didn't initialize it, the compiler would have errored/warned because you could get to the point of incrementing the table without having initialized it (and you'd have spotted this bug).
