### ISSUE TITLE
Bono quiescing may not be thread-safe when using websockets

### ISSUE THREAD

**Issue by johadalin** [Metaswitch/sprout#1455]
Quiescing Bono with websockets active leads to the connection_tracker quiesce function being called on a websockets thread.

#### Steps to reproduce
On a freshly started Bono, having not seen any SIP traffic, quiescing Bono while a WebRTC client is logged in. Wait a short period, and then log out of the WebRTC client.
(Extra logs added for diagnostic purposes)

#### Symptoms

When the quiescing signal is received, there are no initial calls into the connection_tracker->quiesce() function. 
When the WebRTC client logs out, the function is called on a websockets thread, as opposed to the pjsip transport thread. 
Bono is then killed by monit shortly after (this is likely similar to/the same as  https://github.com/Metaswitch/sprout/issues/1296#issuecomment-184167977 ).

#### Impact

It is not clear if it is safe for the websockets thread to complete the quiescing function. 
If it is not safe, then quiescing could break our thread safety model, but further investigation is required.

#### Release and environment 

Release 99, with locks re-added in connection_tracker, as per https://github.com/Metaswitch/sprout/pull/1454 , and with extra logs added for diagnosis.

#### Diagnostics
When the quiescing signal is sent in, the following is shown in the Bono logs:

```
07-06-2016 10:44:59.301 UTC Status main.cpp:1148: Quiesce signal received
07-06-2016 10:44:59.325 UTC Status stack.cpp:389: Destroyed TCP transport for port 5060
07-06-2016 10:45:03.978 UTC Error connection_tracker.cpp:126: connection_active _lock taken by pjsip
07-06-2016 10:45:03.978 UTC Error connection_tracker.cpp:165: connection_active _lock released by pjsip
07-06-2016 10:45:04.980 UTC Error connection_tracker.cpp:93: connection_state_update _lock taken by pjsip
07-06-2016 10:45:04.980 UTC Error connection_tracker.cpp:110: connection_state_update _lock released by pjsip
07-06-2016 10:45:13.975 UTC Error connection_tracker.cpp:126: connection_active _lock taken by pjsip
07-06-2016 10:45:13.975 UTC Error connection_tracker.cpp:165: connection_active _lock released by pjsip
07-06-2016 10:45:14.978 UTC Error connection_tracker.cpp:93: connection_state_update _lock taken by pjsip
07-06-2016 10:45:14.978 UTC Error connection_tracker.cpp:110: connection_state_update _lock released by pjsip
```

And then on logging out of the WebRTC client:
```
07-06-2016 10:45:25.372 UTC Error connection_tracker.cpp:93: connection_state_update _lock taken by pjsip
07-06-2016 10:45:25.372 UTC Error connection_tracker.cpp:110: connection_state_update _lock released by pjsip
07-06-2016 10:45:30.192 UTC Error connection_tracker.cpp:126: connection_active _lock taken by websockets
07-06-2016 10:45:30.192 UTC Error connection_tracker.cpp:165: connection_active _lock released by websockets
07-06-2016 10:45:30.320 UTC Status stack.cpp:389: Destroyed TCP transport for port 5058
07-06-2016 10:45:30.320 UTC Error connection_tracker.cpp:176: quiesce _lock taken by websockets
07-06-2016 10:45:30.320 UTC Error connection_tracker.cpp:181: Function expected to be called on PJSIP transport thread (pjsip) has been called on different thread (websockets)
07-06-2016 10:45:30.320 UTC Error connection_tracker.cpp:210: quiesce _lock released by websockets
07-06-2016 10:45:30.324 UTC Error connection_tracker.cpp:93: connection_state_update _lock taken by pjsip
07-06-2016 10:45:30.324 UTC Error connection_tracker.cpp:110: connection_state_update _lock released by pjsip

Signal 6 caught

Basic stack dump:
/usr/share/clearwater/bin/bono(_ZN6Logger9backtraceEPKc+0x6d)[0x4e331d]
/usr/share/clearwater/bin/bono(_ZN3Log9backtraceEPKcz+0x10d)[0x59c1ad]
/usr/share/clearwater/bin/bono(_Z14signal_handleri+0x2c)[0x5f6f8c]
/lib/x86_64-linux-gnu/libc.so.6(+0x36cb0)[0x7f81a58eecb0]
/lib/x86_64-linux-gnu/libpthread.so.0(sem_wait+0x2e)[0x7f81a6e0c66e]
/usr/share/clearwater/bin/bono(main+0x92ab)[0x4e078b]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f81a58d9f45]
/usr/share/clearwater/bin/bono[0x4e31bc]

Advanced stack dump (requires gdb):
[New LWP 3815]
[New LWP 3814]
[New LWP 3813]
[New LWP 3812]
[New LWP 3811]
[New LWP 3810]
[New LWP 3809]
[New LWP 3808]
[New LWP 3807]
[New LWP 3806]
[New LWP 3805]
[New LWP 3804]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f81a5978a59 in __libc_waitpid (pid=4484, stat_loc=stat_loc@entry=0x7fff9b4af4e0, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40
40      ../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.

Thread 13 (Thread 0x7f819f54d700 (LWP 3804)):
#0  sem_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/sem_wait.S:85
#1  0x00000000005f7374 in SignalHandler<1>::dispatcher (p=<optimized out>) at ../modules/cpp-common/include/signalhandler.h:160
#2  0x00007f81a6e06184 in start_thread (arg=0x7f819f54d700) at pthread_create.c:312
#3  0x00007f81a59b237d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 12 (Thread 0x7f819ed4c700 (LWP 3805)):
#0  sem_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/sem_wait.S:85
#1  0x00000000005f73c4 in SignalHandler<10>::dispatcher (p=<optimized out>) at ../modules/cpp-common/include/signalhandler.h:160
#2  0x00007f81a6e06184 in start_thread (arg=0x7f819ed4c700) at pthread_create.c:312
#3  0x00007f81a59b237d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 11 (Thread 0x7f819e54b700 (LWP 3806)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
#1  0x00000000005bc6be in HealthChecker::main_thread_function (this=0x26590e0) at ../modules/cpp-common/src/health_checker.cpp:119
#2  0x00000000005bc729 in HealthChecker::static_main_thread_function (health_checker=<optimized out>) at ../modules/cpp-common/src/health_checker.cpp:105
#3  0x00007f81a6e06184 in start_thread (arg=0x7f819e54b700) at pthread_create.c:312
#4  0x00007f81a59b237d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 10 (Thread 0x7f819dd4a700 (LWP 3807)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
#1  0x000000000060cec6 in pop (timeout=1000, item="", this=0x2659ca0) at source/sas_eventq.h:257
#2  SAS::Connection::writer (this=0x2659c80) at source/sas.cpp:246
#3  0x000000000060d159 in SAS::Connection::writer_thread (p=<optimized out>) at source/sas.cpp:230
#4  0x00007f81a6e06184 in start_thread (arg=0x7f819dd4a700) at pthread_create.c:312
#5  0x00007f81a59b237d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 9 (Thread 0x7f8196ceb700 (LWP 3808)):
#0  0x00007f81a59b2a13 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f81a7b2fb16 in ?? () from /usr/lib/x86_64-linux-gnu/libzmq.so.3
#2  0x00007f81a7b541e0 in ?? () from /usr/lib/x86_64-linux-gnu/libzmq.so.3
#3  0x00007f81a6e06184 in start_thread (arg=0x7f8196ceb700) at pthread_create.c:312
#4  0x00007f81a59b237d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 8 (Thread 0x7f81964ea700 (LWP 3809)):
#0  0x00007f81a59b2a13 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f81a7b2fb16 in ?? () from /usr/lib/x86_64-linux-gnu/libzmq.so.3
#2  0x00007f81a7b541e0 in ?? () from /usr/lib/x86_64-linux-gnu/libzmq.so.3
#3  0x00007f81a6e06184 in start_thread (arg=0x7f81964ea700) at pthread_create.c:312
#4  0x00007f81a59b237d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 7 (Thread 0x7f8195ce9700 (LWP 3810)):
#0  0x00007f81a59a4fdd in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f81a7b5c35d in zmq_poll () from /usr/lib/x86_64-linux-gnu/libzmq.so.3
#2  0x00000000005a4bcf in LastValueCache::run (this=0x2d43440) at ../modules/cpp-common/src/zmq_lvc.cpp:165
#3  0x00000000005a5549 in LastValueCache::last_value_cache_entry_func (lvc=<optimized out>) at ../modules/cpp-common/src/zmq_lvc.cpp:301
#4  0x00007f81a6e06184 in start_thread (arg=0x7f8195ce9700) at pthread_create.c:312
#5  0x00007f81a59b237d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 6 (Thread 0x7f81954e8700 (LWP 3811)):
#0  0x00007f81a5978dfd in nanosleep () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f81a5978c94 in __sleep (seconds=0) at ../sysdeps/unix/sysv/linux/sleep.c:137
#2  0x0000000000523957 in ConnectionPool::recycle_connections (this=0x2d83790) at connection_pool.cpp:427
#3  0x0000000000523a29 in ConnectionPool::recycle_thread (p=<optimized out>) at connection_pool.cpp:464
#4  0x00000000006e9bae in thread_main (param=0x265c7a0) at ../src/pj/os_core_unix.c:523
#5  0x00007f81a6e06184 in start_thread (arg=0x7f81954e8700) at pthread_create.c:312
#6  0x00007f81a59b237d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 5 (Thread 0x7f8194ce7700 (LWP 3812)):
#0  0x00007f81a59b2a13 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x000000000053d1f5 in boost::asio::detail::epoll_reactor::run (this=0x7f818c000a70, block=<optimized out>, ops=...) at /usr/include/boost/asio/detail/impl/epoll_reactor.ipp:392
#2  0x0000000000542b5a in do_run_one (ec=..., this_thread=..., lock=..., this=<optimized out>) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:368
#3  boost::asio::detail::task_io_service::run (this=0x7f818c000980, ec=...) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:153
#4  0x00000000005434f5 in run (this=0x7f8194ce6cc0) at /usr/include/boost/asio/impl/io_service.ipp:59
#5  websocketpp::endpoint_base::run_internal (this=0x7f8194ce6cc0) at ../usr/include/websocketpp/endpoint.hpp:53
#6  0x000000000055305e in websocketpp::role::server<websocketpp::endpoint<websocketpp::role::server, websocketpp::socket::plain, websocketpp::log::logger> >::start_listen (this=this@entry=0x7f8194ce6cd0, e=..., num_threads=num_threads@entry=0) at ../usr/include/websocketpp/roles/server.hpp:312
#7  0x00000000005381e3 in listen (num_threads=1, e=..., this=0x7f8194ce6cd0) at ../usr/include/websocketpp/roles/server.hpp:227
#8  websocket_thread (p=<optimized out>) at websockets.cpp:515
#9  0x00000000006e9bae in thread_main (param=0x265c7e8) at ../src/pj/os_core_unix.c:523
#10 0x00007f81a6e06184 in start_thread (arg=0x7f8194ce7700) at pthread_create.c:312
#11 0x00007f81a59b237d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 4 (Thread 0x7f8187fff700 (LWP 3813)):
#0  0x00007f81a59a9c53 in select () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f81a69b3cad in agent_check_and_process () from /usr/lib/x86_64-linux-gnu/libnetsnmpagent.so.30
#2  0x00000000005df642 in snmp_thread (data=<optimized out>) at ../modules/cpp-common/src/snmp_agent.cpp:47
#3  0x00007f81a6e06184 in start_thread (arg=0x7f8187fff700) at pthread_create.c:312
#4  0x00007f81a59b237d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 3 (Thread 0x7f81877fe700 (LWP 3814)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00000000005dd0f8 in pop (item=<synthetic pointer>, this=0x9f3b60 <rx_msg_q>) at ../modules/cpp-common/include/eventq.h:279
#2  worker_thread (p=<optimized out>) at thread_dispatcher.cpp:143
#3  0x00000000006e9bae in thread_main (param=0x265c830) at ../src/pj/os_core_unix.c:523
#4  0x00007f81a6e06184 in start_thread (arg=0x7f81877fe700) at pthread_create.c:312
#5  0x00007f81a59b237d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 2 (Thread 0x7f8186ffd700 (LWP 3815)):
#0  0x00007f81a59b2a13 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x00000000006e853e in pj_ioqueue_poll (ioqueue=0x7f819c2404d0, timeout=0x7f8186ffce30) at ../src/pj/ioqueue_epoll.c:690
#2  0x000000000066ca83 in pjsip_endpt_handle_events2 (endpt=0x7f819c2370b8, max_timeout=0x7f8186ffce70, p_count=0x0) at ../src/pjsip/sip_endpoint.c:740
#3  0x000000000066cb2f in pjsip_endpt_handle_events (endpt=0x7f819c2370b8, max_timeout=0x7f8186ffce70) at ../src/pjsip/sip_endpoint.c:768
#4  0x00000000004e6e2f in pjsip_thread_func (p=<optimized out>) at stack.cpp:180
#5  0x00000000006e9bae in thread_main (param=0x265c878) at ../src/pj/os_core_unix.c:523
#6  0x00007f81a6e06184 in start_thread (arg=0x7f8186ffd700) at pthread_create.c:312
#7  0x00007f81a59b237d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 1 (Thread 0x7f81a8cea780 (LWP 3803)):
#0  0x00007f81a5978a59 in __libc_waitpid (pid=4484, stat_loc=stat_loc@entry=0x7fff9b4af4e0, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40
#1  0x00007f81a58fe232 in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:148
#2  0x00000000004e33d3 in Logger::backtrace (this=0x26478e0, data=<optimized out>) at ../modules/cpp-common/src/logger.cpp:318
#3  0x000000000059c1ad in Log::backtrace (fmt=fmt@entry=0x73f7d8 "Signal %d caught") at ../modules/cpp-common/src/log.cpp:185
#4  0x00000000005f6f8c in signal_handler (sig=6) at main.cpp:1126
#5  <signal handler called>
#6  sem_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/sem_wait.S:84
#7  0x00000000004e078b in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:2128
Couldn't write debug register: No such process.
```

**Comment by johadalin** [comment]
If we decide that it is safe for websocket threads to call into quiesce, we should update the CHECK_PJ_TRANSPORT_THREAD call so that we do not raise spurious error logs, as in #1454
