### ISSUE TITLE
Memento crashes due to missing CassandraResolver

### ISSUE THREAD

**Issue by AlexHockey** [Metaswitch/sprout#1546]
#### Symptoms

Memento crashes when it processes a call. 

```
#0  0x00007fecf5b31b99 in __libc_waitpid (pid=532, stat_loc=stat_loc@entry=0x7fecbeff9aa0, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40
#1  0x00007fecf5ab72e2 in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:148
#2  0x00000000004e5dc3 in Logger::backtrace (this=0x228ff00, data=<optimized out>) at ../modules/cpp-common/src/logger.cpp:318
#3  0x00000000005a2a7d in Log::backtrace (fmt=fmt@entry=0x747178 "Signal %d caught") at ../modules/cpp-common/src/log.cpp:185
#4  0x00000000005fdb2c in signal_handler (sig=11) at main.cpp:1151
#5  <signal handler called>
#6  0x00007fecdc5c5246 in CassandraStore::Store::perform_op (this=this@entry=0x3175fa0, op=op@entry=0x7fece81a9290, trail=trail@entry=1392, cass_result=@0x7fecbeffcc4c: CassandraStore::UNKNOWN_ERROR, cass_error_text=...) at ../modules/cpp-common/src/cassandra_store.cpp:287
#7  0x00007fecdc5c5d61 in CassandraStore::Store::do_sync (this=0x3175fa0, op=0x7fece81a9290, trail=1392) at ../modules/cpp-common/src/cassandra_store.cpp:390
#8  0x00007fecdc5d4db3 in CallListStore::Store::write_call_fragment_sync (this=0x3175fa0, impu=..., fragment=..., cass_timestamp=<optimized out>, ttl=<optimized out>, trail=1392) at ../modules/memento-as/modules/memento-common/src/call_list_store.cpp:446
#9  0x00007fecdc5d9038 in CallListStoreProcessor::Pool::process_work (this=0x3176900, clr=@0x7fecbeffcdd8: 0x7fec8817b180) at ../modules/memento-as/src/call_list_store_processor.cpp:124
#10 0x00007fecdc5da4d4 in ThreadPool<CallListStoreProcessor::CallListRequest*>::worker_thread_func (this=0x3176900) at ../modules/cpp-common/include/threadpool.h:184
#11 0x00007fecdc5da5b9 in ThreadPool<CallListStoreProcessor::CallListRequest*>::static_worker_thread_func (pool=<optimized out>) at ../modules/cpp-common/include/threadpool.h:162
#12 0x00007fecf6fbf182 in start_thread (arg=0x7fecbeffd700) at pthread_create.c:312
#13 0x00007fecf5b6b47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

This is because we configure the call list store without a Cassandra resolver (see https://github.com/Metaswitch/sprout/blob/777de6d5f06915ac274936e85d5e996cd6be695d/src/mementoasplugin.cpp#L112)

#### Impact

Memento doesn't work. 

#### Release and environment 

Current dev (https://github.com/Metaswitch/sprout/commit/fc9ff1ffd4bdad5b8b9863ee5206b32f3390ed0b)

#### Steps to reproduce

* Create a sprout node. 
* Install memento
* Configure a subscriber to use memento.
* Make a call from that subscriber.

**Comment by sebrexmetaswitch** [comment]
Fixed  by #1547
