### ISSUE TITLE
Shutting down one Sprout VM of a duplex pair causes calls to fail for 10 seconds

### ISSUE THREAD

**Issue by AME2** [Metaswitch/sprout#1657]
I was doing some resiliency testing using a deployment with two Sprouts, two Homesteads and a Ralf. I was using clearwater-live-test-ccst to generate ten calls between two subscribers I had provisioned on a HSS. During these calls I shut down the guest OS on one of the Sprout nodes. I didn't expect this to have any impact on the tests.

#### Symptoms
What actually happened was that a few seconds after I had shut down the Sprout nodes one of the calls would fail. The next call after this would usually work.

Clearwater-live-test-ccst gave me the following output:

```
   - Expected 401|200, got 503
     - /home/ubuntu/clearwater-live-test-ccst/.bundle/ruby/1.9.1/bundler/gems/quaff-private-40f2c742b45a/lib/call.rb:212:in `recv_response'
     - /home/ubuntu/clearwater-live-test-ccst/.bundle/ruby/1.9.1/bundler/gems/quaff-private-40f2c742b45a/lib/endpoint.rb:175:in `register'
     - /home/ubuntu/clearwater-live-test-ccst/.bundle/ruby/1.9.1/bundler/gems/quaff-private-40f2c742b45a/lib/endpoint.rb:194:in `unregister'
     - /home/ubuntu/clearwater-live-test-ccst/lib/tests/basic-call.rb:96:in `block (2 levels) in <top (required)>'
     - /home/ubuntu/clearwater-live-test-ccst/lib/test-definition.rb:465:in `call'
     - /home/ubuntu/clearwater-live-test-ccst/lib/test-definition.rb:465:in `cleanup'
     - /home/ubuntu/clearwater-live-test-ccst/lib/test-definition.rb:271:in `ensure in run'
     - /home/ubuntu/clearwater-live-test-ccst/lib/test-definition.rb:272:in `run'
     - /home/ubuntu/clearwater-live-test-ccst/lib/test-definition.rb:126:in `block (2 levels) in run_all'
     - /home/ubuntu/clearwater-live-test-ccst/lib/test-definition.rb:112:in `collect'
     - /home/ubuntu/clearwater-live-test-ccst/lib/test-definition.rb:112:in `block in run_all'
     - /home/ubuntu/clearwater-live-test-ccst/lib/test-definition.rb:111:in `each'
     - /home/ubuntu/clearwater-live-test-ccst/lib/test-definition.rb:111:in `run_all'
     - /home/ubuntu/clearwater-live-test-ccst/lib/live-test.rb:20:in `run_tests'
     - /home/ubuntu/clearwater-live-test-ccst/Rakefile:13:in `block in <top (required)>'
     - /home/ubuntu/clearwater-live-test-ccst/.bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
     - /home/ubuntu/clearwater-live-test-ccst/.bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
     - /home/ubuntu/clearwater-live-test-ccst/.bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
     - /home/ubuntu/clearwater-live-test-ccst/.bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
     - /home/ubuntu/clearwater-live-test-ccst/.bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
     - /home/ubuntu/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
     - /home/ubuntu/clearwater-live-test-ccst/.bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
     - /home/ubuntu/clearwater-live-test-ccst/.bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
     - /home/ubuntu/clearwater-live-test-ccst/.bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
     - /home/ubuntu/clearwater-live-test-ccst/.bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
     - /home/ubuntu/clearwater-live-test-ccst/.bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
     - /home/ubuntu/clearwater-live-test-ccst/.bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
     - /home/ubuntu/clearwater-live-test-ccst/.bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
     - /home/ubuntu/clearwater-live-test-ccst/.bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
     - /home/ubuntu/clearwater-live-test-ccst/.bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
     - /home/ubuntu/clearwater-live-test-ccst/.bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     - /home/ubuntu/clearwater-live-test-ccst/.bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
     - /home/ubuntu/clearwater-live-test-ccst/.bundle/ruby/1.9.1/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
     - /home/ubuntu/clearwater-live-test-ccst/.bundle/ruby/1.9.1/bin/rake:23:in `load'
     - /home/ubuntu/clearwater-live-test-ccst/.bundle/ruby/1.9.1/bin/rake:23:in `<main>'
```

It looks as though the "Basic Call - Mainline" test failed at the point where you register subscribers before a phone call. Attached is the SAS trace of the failed registration.

[Killing Sprout.zip](https://github.com/Metaswitch/sprout/files/666538/Killing.Sprout.zip)

I further verified this by trying to register a subscriber using a soft-phone client. I found that for about 10 seconds after killing the Sprout node that I unable to register. Attached is a SAS trace showing the registration attempt.

[Killing Sprout Blink.zip](https://github.com/Metaswitch/sprout/files/666572/Killing.Sprout.Blink.zip)

Note: This has about a 50% reproduction rate, sometimes the live tests all pass and sometimes subscribers just take longer to register. 

#### Impact
This could stop calls from being made. Shutting down a Sprout node doesn't seem to drop calls that are already in progress. Seeing as the outage is over quite a short period subscribers would probably attempt the call again and it would be successful.

#### Release and environment 
2 Sprouts: 10.0.0-161216-~255.00.0
2 Homesteads: 10.0.0-161216-~255.00.0
1 Ralf: 10.0.0-161216-~255.00.0
1 real external HSS
1 clearwater-live-test-ccst node

#### Steps to reproduce
Create a Clearwater deployment as above. Start a live test job that would make ten phone calls. As this job starts shut down the OS on one of the Sprout nodes in the deployment.

**Comment by rkd-msw** [comment]
I think this turned out to be due to a P-CSCF misconfiguration (and/or a P-CSCF bug) - can you close if you agree?

**Comment by AME2** [comment]
Yes I agree
