### ISSUE TITLE
poll_sprout_sip failures (causing Monit to kill Sprout) when AS is rebooted

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/sprout#1728]
#### Symptoms

I ran REGISTER stress, with an AS receiving third-party registrations, and rebooted the AS. Monit then killed my Sprout node.

Specifically, I rebooted the AS at 13:21:19 GMT, and then saw this in /var/log/monit.log:

```
[UTC Feb  6 13:21:43] error    : 'poll_sprout_sip' '/usr/share/clearwater/bin/poll_sprout_sip.sh' failed with exit status (1) -- SIP poll failed to 10.225.166.238:5054 with Call-ID poll-sip-516180 at 2017-02-06 13:21:33.898705432+00:00
stderr was:
Connection to 10.225.166.238 5054 port [tcp/*] succeeded!
stdout was:
[UTC Feb  6 13:21:43] info     : 'poll_sprout_sip' exec: /bin/bash
[UTC Feb  6 13:21:53] error    : 'sprout_process' process is not running
[UTC Feb  6 13:21:53] info     : 'sprout_process' trying to restart
[UTC Feb  6 13:21:53] info     : 'sprout_process' restart: /bin/bash
[UTC Feb  6 13:21:54] error    : 'poll_sprout_sip' '/usr/share/clearwater/bin/poll_sprout_sip.sh' failed with exit status (1) -- SIP poll failed to 10.225.166.238:5054 with Call-ID poll-sip-516190 at 2017-02-06 13:21:43.924112852+00:00
stderr was:
Connection to 10.225.166.238 5054 port [tcp/*] succeeded!
stdout was:
[UTC Feb  6 13:22:04] info     : 'sprout_process' process is running with pid 12529
[UTC Feb  6 13:22:24] error    : 'sprout_uptime' '/usr/share/clearwater/infrastructure/monit_uptime/check-sprout-uptime' failed with exit status (1) -- no output
[UTC Feb  6 13:22:54] info     : 'sprout_uptime' status succeeded [status=0] -- no output
```

I'd guess that all my threads are getting blocked waiting for a connection to the AS to time out.

#### Impact

In-progress transactions fail.

#### Release and environment 

10.0.0-170131-~255.00.0-170131.020417

#### Steps to reproduce

Run REGISTER stress. Reboot the AS receiving third-party registrations.

**Comment by sebrexmetaswitch** [comment]
For some reason I couldn't see the thread dump that should have been generated in the above case when sprout was killed, but Rob gave me a test system that repros it, and I found that it looks like we're failing the health check because we're doing a bunch of HTTP requests on the main thread.

After a repro, I got the following thread dump:

```
Thread 109 (Thread 0x7fb137786700 (LWP 7042)):
#0  0x00007fb19c21112d in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fb19d93dd89 in Curl_poll () from /usr/share/clearwater/sprout/lib/libcurl.so.4
#2  0x00007fb19d9390dc in curl_multi_wait () from /usr/share/clearwater/sprout/lib/libcurl.so.4
#3  0x00007fb19d933697 in curl_easy_perform () from /usr/share/clearwater/sprout/lib/libcurl.so.4
#4  0x0000000000563a84 in HttpClient::send_request (this=<optimized out>, request_type=HttpClient::PUT, url="http://homestead.rkd.clearwater.test:8888/impu/sip%3A48150961037%40rkd.clearwater.test/reg-data", body="{\"reqtype\": \"dereg-admin\", \"server_name\": \"sip:scscf.sprout.rkd.clearwater.test;transport=TCP\"}", doc="", username="", trail=17949, headers_to_add=std::vector of length 0, capacity 0, response_headers=0x7fb137785450) at ../modules/cpp-common/src/httpclient.cpp:502
Python Exception <class 'IndexError'> list index out of range: 
#5  0x00000000005605c5 in HttpClient::send_put (this=this@entry=0x2b2a148, url="http://homestead.rkd.clearwater.test:8888/impu/sip%3A48150961037%40rkd.clearwater.test/reg-data", headers=std::map with 0 elements, response="", body="{\"reqtype\": \"dereg-admin\", \"server_name\": \"sip:scscf.sprout.rkd.clearwater.test;transport=TCP\"}", extra_req_headers=std::vector of length 0, capacity 0, trail=trail@entry=17949, username="") at ../modules/cpp-common/src/httpclient.cpp:246
Python Exception <class 'IndexError'> list index out of range: 
#6  0x00000000005662d8 in HttpConnection::send_put (this=0x2b2a130, path="/impu/sip%3A48150961037%40rkd.clearwater.test/reg-data", headers=std::map with 0 elements, response="", body="{\"reqtype\": \"dereg-admin\", \"server_name\": \"sip:scscf.sprout.rkd.clearwater.test;transport=TCP\"}", extra_req_headers=std::vector of length 0, capacity 0, trail=trail@entry=17949, username="") at ../modules/cpp-common/src/httpconnection.cpp:125
#7  0x0000000000569376 in HSSConnection::put_for_xml_object (this=this@entry=0x2b27e30, path="/impu/sip%3A48150961037%40rkd.clearwater.test/reg-data", body="{\"reqtype\": \"dereg-admin\", \"server_name\": \"sip:scscf.sprout.rkd.clearwater.test;transport=TCP\"}", cache_allowed=cache_allowed@entry=true, root=@0x7fb137785548: 0x0, trail=trail@entry=17949) at hssconnection.cpp:229
Python Exception <class 'IndexError'> list index out of range: 
#8  0x000000000056a6b6 in HSSConnection::update_registration_state (this=this@entry=0x2b27e30, public_user_identity="sip:48150961037@rkd.clearwater.test", private_user_identity="", type="dereg-admin", regstate="", ifcs_map=std::map with 0 elements, associated_uris=std::vector of length 1, capacity 1 = {...}, aliases=std::vector of length 0, capacity 0, ccfs=std::deque with 0 elements, ecfs=std::deque with 0 elements, cache_allowed=cache_allowed@entry=true, trail=trail@entry=17949) at hssconnection.cpp:624
Python Exception <class 'IndexError'> list index out of range: 
#9  0x000000000056b03a in HSSConnection::update_registration_state (this=this@entry=0x2b27e30, public_user_identity="sip:48150961037@rkd.clearwater.test", private_user_identity="", type="dereg-admin", ifcs_map=std::map with 0 elements, associated_uris=std::vector of length 1, capacity 1 = {...}, trail=trail@entry=17949) at hssconnection.cpp:536
#10 0x000000000054d7e9 in RegistrationUtils::remove_bindings (sdm=0x2b2dc90, remote_sdms=std::vector of length 1, capacity 1 = {...}, hss=hss@entry=0x2b27e30, aor="sip:48150961037@rkd.clearwater.test", binding_id="*", dereg_type="dereg-admin", trail=trail@entry=17949, hss_status_code=hss_status_code@entry=0x0) at registration_utils.cpp:515
#11 0x000000000054e38e in third_party_register_failed (public_id="sip:48150961037@rkd.clearwater.test", trail=17949) at registrar.cpp:1128
#12 0x000000000054ce61 in send_register_cb (token=0x7fb17c63b170, event=<optimized out>) at registration_utils.cpp:229
#13 0x00000000005d7f94 in on_tsx_state (tsx=0x7fb17c4e8548, event=0x7fb137785a80) at pjutils.cpp:1168
#14 0x0000000000767dd8 in tsx_set_state (tsx=0x7fb17c4e8548, state=PJSIP_TSX_STATE_TERMINATED, event_src_type=PJSIP_EVENT_TRANSPORT_ERROR, event_src=0x7fb17c521038) at ../src/pjsip/sip_transaction.c:1199
#15 0x000000000076954d in send_msg_callback (send_state=0x7fb17c4e7a40, sent=-70009, cont=0x7fb137785bcc) at ../src/pjsip/sip_transaction.c:1881
#16 0x0000000000753cfa in stateless_send_transport_cb (token=0x7fb17c4e7a40, tdata=0x7fb17c521038, sent=-70009) at ../src/pjsip/sip_util.c:1112
#17 0x00000000007589c7 in transport_send_callback (transport=0x7fb1301ff898, token=0x7fb17c521038, size=-70009) at ../src/pjsip/sip_transport.c:773
#18 0x000000000075fb6a in on_data_sent (asock=0x7fb130150540, op_key=0x7fb17c521090, bytes_sent=-70009) at ../src/pjsip/sip_transport_tcp.c:1203
#19 0x0000000000760489 in on_connect_complete (asock=0x7fb130150540, status=70009) at ../src/pjsip/sip_transport_tcp.c:1556
#20 0x0000000000760736 in tcp_connect_timer (th=0x7fb1900923f0, e=0x7fb1301ffa08) at ../src/pjsip/sip_transport_tcp.c:1637
#21 0x00000000007ddccc in pj_timer_heap_poll (ht=0x7fb1900923f0, next_delay=0x7fb137785e30) at ../src/pj/timer.c:643
#22 0x0000000000750615 in pjsip_endpt_handle_events2 (endpt=0x7fb1900920b8, max_timeout=0x7fb137785e70, p_count=0x0) at ../src/pjsip/sip_endpoint.c:711
#23 0x0000000000750785 in pjsip_endpt_handle_events (endpt=0x7fb1900920b8, max_timeout=0x7fb137785e70) at ../src/pjsip/sip_endpoint.c:768
#24 0x00000000005199ff in pjsip_thread_func (p=<optimized out>) at stack.cpp:180
#25 0x00000000007cd8fd in thread_main (param=0x2c6b1f8) at ../src/pj/os_core_unix.c:523
#26 0x00007fb19d45d182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#27 0x00007fb19c21e47d in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

This is the main PJSIP thread (because we see `pjsip_thread_func (p=<optimized out>) at stack.cpp:180`)

We see that the TCP connection timed out (which happens after 2s). This results in a call to `on_tsx_state` on this thread, which is expected. The problem is that, for a 3rd party REGISTER, we set a callback when we send the REGISTER: https://github.com/Metaswitch/sprout/blob/release-114-fixes/src/registration_utils.cpp#L409

This callback is run on the same thread as gets the `on_tsx_state callback`: https://github.com/Metaswitch/sprout/blob/release-114-fixes/src/pjutils.cpp#L1168

Because the IFCs in use specify Session Terminate as the default handling, this callback involves administratively de-registering the subscriber, which means an HTTP request to homestead. This is a problem because out HTTP requests are blocking.

(Note: I was worried at first when I saw that SIP retries to other servers are also handled in `on_tsx_state`, but that's actually OK because the `pjsip_tsx_send_msg` is actually going to send asynchronously)

All of the above means that this is a problem when all of the following are true:
- the App Server is being used for 3rd-party registrations
- the IFCs specify Session Terminate  as the default handling (so that the failure to contact the AS will result in de-registration)
- **all** of the App Servers are uncontactable (if only one is down, then the requests will be retried to the working server and succeed, and the dead server will be blacklisted for a period)

Any fix for this is likely to be fairly large, so the next step is to establish whether we want to risk fixing this at this point
